<?php

return [
    'links' => [
        'github' => 'https://github.com/muhfajri24',
        'linkedin' => 'https://www.linkedin.com/in/muhammad-fajri-349821287',
    ],
    'ui' => [
        'id' => [
            'lang' => 'id',
            'languageShort' => 'ID',
            'languageLabel' => 'Bahasa Indonesia',
            'nav' => [
                'about' => 'Tentang',
                'skills' => 'Skill',
                'experience' => 'Pengalaman',
                'education' => 'Pendidikan',
                'projects' => 'Project',
                'contact' => 'Kontak',
            ],
            'heroEyebrow' => 'Data Scientist Portfolio',
            'aboutEyebrow' => 'Tentang Saya',
            'aboutHeading' => 'Perjalanan teknis, organisasi, dan pembelajaran yang terus bergerak maju',
            'skillsEyebrow' => 'Skill',
            'skillsHeading' => 'Kemampuan teknis dan cara kerja yang saya bawa ke setiap kolaborasi',
            'experienceEyebrow' => 'Pengalaman',
            'experienceHeading' => 'Pengalaman profesional dan organisasi yang membentuk cara saya bekerja',
            'educationEyebrow' => 'Pendidikan',
            'educationHeading' => 'Fondasi akademik yang mendukung eksplorasi teknologi',
            'projectsEyebrow' => 'Project',
            'projectsHeading' => 'Project yang menunjukkan workflow data, machine learning, dan dampak analitis',
            'projectsDescription' => 'Bagian ini menampilkan project yang saya gunakan untuk mengasah supervised learning, unsupervised learning, NLP, time series forecasting, dan analisis data yang siap dipresentasikan.',
            'projectFilterLabel' => 'Filter Project',
            'contactEyebrow' => 'Kontak',
            'contactHeading' => 'Mari terhubung untuk kolaborasi, internship, atau peluang kerja',
            'contactSummary' => 'Saya terbuka untuk peluang data scientist, machine learning, data science, dan backend yang membutuhkan eksekusi teknis sekaligus komunikasi yang rapi.',
            'infoTitle' => 'Info Singkat',
            'noteLabel' => 'Fokus Saat Ini',
            'noteTitle' => 'Data scientist focus',
            'noteText' => 'Saat ini saya membangun fondasi di machine learning, forecasting, NLP, dan analisis data sambil tetap membawa pengalaman backend yang rapi dan terstruktur.',
            'githubButton' => 'Lihat GitHub',
            'linkedinButton' => 'LinkedIn',
            'footer' => 'Dibangun ulang dengan Laravel, Blade, CSS, dan JavaScript agar struktur backend lebih rapi tanpa kehilangan pengalaman interaktif di sisi frontend.',
            'projectLink' => 'Highlight',
            'projectActions' => [
                'website' => 'Buka Demo',
                'repository' => 'Buka Repository',
                'comingSoon' => 'Buka Repository',
            ],
            'projectFilters' => [
                ['value' => 'all', 'label' => 'Semua'],
                ['value' => 'web', 'label' => 'Web'],
                ['value' => 'machine-learning', 'label' => 'Machine Learning'],
                ['value' => 'analytics', 'label' => 'Data Science'],
            ],
            'stats' => [
                ['value' => '6+', 'label' => 'Pengalaman organisasi & profesional'],
                ['value' => '10', 'label' => 'Project publik yang aktif ditampilkan'],
                ['value' => '2023-', 'label' => 'Perjalanan akademik informatika'],
            ],
        ],
        'en' => [
            'lang' => 'en',
            'languageShort' => 'EN',
            'languageLabel' => 'English',
            'nav' => [
                'about' => 'About',
                'skills' => 'Skills',
                'experience' => 'Experience',
                'education' => 'Education',
                'projects' => 'Projects',
                'contact' => 'Contact',
            ],
            'heroEyebrow' => 'Data Scientist Portfolio',
            'aboutEyebrow' => 'About Me',
            'aboutHeading' => 'A growing journey across technical work, organizations, and continuous learning',
            'skillsEyebrow' => 'Skills',
            'skillsHeading' => 'Technical capabilities and working style I bring into each collaboration',
            'experienceEyebrow' => 'Experience',
            'experienceHeading' => 'Professional and organizational experiences that shape how I work',
            'educationEyebrow' => 'Education',
            'educationHeading' => 'Academic foundations that support my technology exploration',
            'projectsEyebrow' => 'Projects',
            'projectsHeading' => 'Projects that show data workflows, machine learning, and analytical impact',
            'projectsDescription' => 'This section highlights the projects I use to strengthen supervised learning, unsupervised learning, NLP, time series forecasting, and presentation-ready data analysis.',
            'projectFilterLabel' => 'Project Filter',
            'contactEyebrow' => 'Contact',
            'contactHeading' => 'Let us connect for collaboration, internships, or career opportunities',
            'contactSummary' => 'I am open to data scientist, machine learning, data science, and backend opportunities that need both technical execution and clear communication.',
            'infoTitle' => 'Quick Info',
            'noteLabel' => 'Current Focus',
            'noteTitle' => 'Data scientist focus',
            'noteText' => 'I am currently building stronger foundations in machine learning, forecasting, NLP, and data analysis while still bringing structured backend experience.',
            'githubButton' => 'View GitHub',
            'linkedinButton' => 'LinkedIn',
            'footer' => 'Rebuilt with Laravel, Blade, CSS, and JavaScript so the backend structure is cleaner without losing the interactive frontend experience.',
            'projectLink' => 'Highlight',
            'projectActions' => [
                'website' => 'Open Demo',
                'repository' => 'Open Repository',
                'comingSoon' => 'Open Repository',
            ],
            'projectFilters' => [
                ['value' => 'all', 'label' => 'All'],
                ['value' => 'web', 'label' => 'Web'],
                ['value' => 'machine-learning', 'label' => 'Machine Learning'],
                ['value' => 'analytics', 'label' => 'Data Science'],
            ],
            'stats' => [
                ['value' => '6+', 'label' => 'Professional and organizational roles'],
                ['value' => '10', 'label' => 'Public projects actively showcased'],
                ['value' => '2023-', 'label' => 'Academic journey in informatics'],
            ],
        ],
    ],
    'personal' => [
        'name' => 'Muhammad Fajri',
        'image' => '/assets/Profile.jpeg',
        'role' => [
            'id' => 'Mahasiswa Informatika yang berfokus pada Data Scientist track melalui machine learning, forecasting, NLP, dan project berbasis data.',
            'en' => 'An Informatics student focused on the Data Scientist track through machine learning, forecasting, NLP, and data-driven projects.',
        ],
        'summary' => [
            'id' => 'Saya membangun web ini untuk menunjukkan bagaimana saya mengubah data mentah menjadi model, insight, dan output yang siap dipakai untuk pengambilan keputusan, sambil tetap membawa fondasi backend dan engineering yang rapi.',
            'en' => 'I built this website to show how I turn raw data into models, insights, and decision-ready outputs while still bringing a clean backend and engineering foundation.',
        ],
        'about' => [
            'id' => 'Saya terbiasa belajar lewat studi kasus, mengerjakan project end-to-end, dan menjaga agar solusi tetap mudah dipahami. Saat ini fokus utama saya adalah berkembang ke arah Data Scientist melalui project klasifikasi, segmentasi, forecasting, dan NLP yang tidak berhenti di model saja, tetapi juga sampai ke insight bisnis dan output yang siap dipresentasikan. Pengalaman organisasi membuat saya nyaman memimpin, berkoordinasi, dan mengambil keputusan secara kolaboratif, sementara pengalaman backend membantu saya tetap disiplin dalam merapikan struktur solusi. Bagi saya, project yang baik adalah project yang kuat secara analitis, jelas alurnya, dan berguna untuk pengambilan keputusan nyata.',
            'en' => 'I am used to learning through case studies, completing projects end-to-end, and keeping solutions easy to understand. My current focus is to grow toward Data Scientist roles through classification, segmentation, forecasting, and NLP projects that do not stop at model building, but continue into business insight and presentation-ready outputs. My organizational experience makes me comfortable leading, coordinating, and making collaborative decisions, while my backend experience keeps me disciplined around solution structure. For me, a strong project is one that is analytically solid, clear in flow, and useful for real decision making.',
        ],
        'currentLabel' => [
            'id' => 'Sorotan Peran',
            'en' => 'Featured Role',
        ],
        'currentTitle' => [
            'id' => 'Backend Developer Intern',
            'en' => 'Backend Developer Intern',
        ],
        'currentSubtitle' => [
            'id' => 'Telkom Indonesia | Januari 2026 - Mei 2026',
            'en' => 'Telkom Indonesia | January 2026 - May 2026',
        ],
        'highlights' => [
            'id' => [
                'Magang Backend Developer di Telkom Indonesia pada Januari 2026 - Mei 2026.',
                'Ketua BPM HIMAIF Universitas Telkom sejak Maret 2026.',
                'Ketua UKM Paskibra Universitas Telkom sepanjang 2025.',
            ],
            'en' => [
                'Backend Developer Intern at Telkom Indonesia from January 2026 to May 2026.',
                'Chair of BPM HIMAIF Telkom University since March 2026.',
                'President of UKM Paskibra Telkom University throughout 2025.',
            ],
        ],
        'focus' => [
            'id' => ['Data Scientist', 'Machine Learning', 'Backend Foundation'],
            'en' => ['Data Scientist', 'Machine Learning', 'Backend Foundation'],
        ],
    ],
    'quickInfo' => [
        'id' => [
            ['title' => 'Domisili', 'value' => 'Kabupaten Bandung, Jawa Barat'],
            ['title' => 'Email', 'value' => 'muhfajrmlk@gmail.com'],
            ['title' => 'Telepon', 'value' => '0823-3318-8437'],
            ['title' => 'Alamat', 'value' => 'Bojongsoang, Bandung'],
            ['title' => 'Kampus', 'value' => 'Universitas Telkom'],
            ['title' => 'Fokus', 'value' => 'Data scientist, machine learning, forecasting, NLP, dan analytics'],
        ],
        'en' => [
            ['title' => 'Location', 'value' => 'Bandung Regency, West Java'],
            ['title' => 'Email', 'value' => 'muhfajrmlk@gmail.com'],
            ['title' => 'Phone', 'value' => '0823-3318-8437'],
            ['title' => 'Address', 'value' => 'Bojongsoang, Bandung'],
            ['title' => 'University', 'value' => 'Telkom University'],
            ['title' => 'Focus', 'value' => 'Data scientist, machine learning, forecasting, NLP, and analytics'],
        ],
    ],
    'skills' => [
        'id' => [
            ['title' => 'Backend & Framework', 'items' => ['Laravel', 'PHP', 'REST API Dasar', 'JSON']],
            ['title' => 'Bahasa Pemrograman', 'items' => ['Python', 'PHP', 'C++', 'Go']],
            ['title' => 'Machine Learning & AI', 'items' => ['Scikit-learn', 'XGBoost', 'NLP', 'Forecasting']],
            ['title' => 'Web Development', 'items' => ['HTML', 'CSS', 'JavaScript', 'Blade']],
            ['title' => 'Data & Visualisasi', 'items' => ['Pandas', 'Matplotlib', 'Seaborn', 'Power BI']],
            ['title' => 'Cara Kerja', 'items' => ['Analitis', 'Kepemimpinan', 'Kolaboratif', 'Adaptif']],
        ],
        'en' => [
            ['title' => 'Backend & Framework', 'items' => ['Laravel', 'PHP', 'Basic REST API', 'JSON']],
            ['title' => 'Programming Languages', 'items' => ['Python', 'PHP', 'C++', 'Go']],
            ['title' => 'Machine Learning & AI', 'items' => ['Scikit-learn', 'XGBoost', 'NLP', 'Forecasting']],
            ['title' => 'Web Development', 'items' => ['HTML', 'CSS', 'JavaScript', 'Blade']],
            ['title' => 'Data & Visualization', 'items' => ['Pandas', 'Matplotlib', 'Seaborn', 'Power BI']],
            ['title' => 'Work Style', 'items' => ['Analytical', 'Leadership', 'Collaborative', 'Adaptive']],
        ],
    ],
    'experiences' => [
        'id' => [
            [
                'period' => 'Mar 2026 - Sekarang',
                'role' => 'Ketua BPM',
                'company' => 'BPM HIMAIF - Universitas Telkom',
                'description' => 'Memimpin badan legislatif HIMA IF serta menjaga arah kebijakan, pengawasan, dan koordinasi program kerja organisasi.',
                'highlights' => [
                    'Memimpin badan legislatif HIMA IF.',
                    'Menyelaraskan pengawasan organisasi dengan visi dan misi kelembagaan.',
                    'Berkoordinasi dengan dewan dan komite untuk menjaga eksekusi program kerja.',
                ],
            ],
            [
                'period' => 'Jan 2026 - Mei 2026',
                'role' => 'Magang Backend Developer',
                'company' => 'Telkom Indonesia',
                'description' => 'Berkontribusi pada integrasi layanan backend dan status monitoring perangkat untuk sistem chatbot selama masa magang.',
                'highlights' => [
                    'Membantu pembuatan API.',
                    'Mengelola data status perangkat seperti aktif, nonaktif, dan tidak terdeteksi.',
                    'Berkolaborasi dengan tim frontend pada widget obrolan dan dashboard monitoring.',
                ],
            ],
            [
                'period' => 'Apr 2025 - Mar 2026',
                'role' => 'Staff Ahli Komisi Etik',
                'company' => 'BPM HIMAIF - Universitas Telkom',
                'description' => 'Mendukung pemantauan kode etik organisasi, evaluasi kebijakan internal, dan pengambilan keputusan yang lebih terstruktur.',
                'highlights' => [
                    'Mendukung evaluasi kode etik organisasi.',
                    'Berpartisipasi dalam diskusi kebijakan internal.',
                ],
            ],
            [
                'period' => 'Jan 2025 - Des 2025',
                'role' => 'Ketua UKM Paskibra',
                'company' => 'UKM Paskibra Universitas Telkom',
                'description' => 'Memimpin perencanaan, eksekusi, dan representasi organisasi dalam forum resmi maupun kegiatan internal.',
                'highlights' => [
                    'Mengoordinasikan anggota dan agenda kerja.',
                    'Mewakili organisasi dalam forum resmi.',
                ],
            ],
        ],
        'en' => [
            [
                'period' => 'Mar 2026 - Present',
                'role' => 'Chair of the BPM',
                'company' => 'BPM HIMAIF - Telkom University',
                'description' => 'Leading the HIMA IF legislative body while maintaining policy direction, oversight, and work-program coordination.',
                'highlights' => [
                    'Leads the HIMA IF legislative body.',
                    'Aligns organizational oversight with institutional goals.',
                    'Coordinates with councils and committees to sustain program execution.',
                ],
            ],
            [
                'period' => 'Jan 2026 - May 2026',
                'role' => 'Backend Developer Intern',
                'company' => 'Telkom Indonesia',
                'description' => 'Contributed to backend service integration and device-status monitoring for a chatbot system during the internship.',
                'highlights' => [
                    'Helped build APIs.',
                    'Handled device-status data such as up, down, and undetected.',
                    'Collaborated with the frontend team on chat widgets and monitoring dashboards.',
                ],
            ],
            [
                'period' => 'Apr 2025 - Mar 2026',
                'role' => 'Senior Advisor to the Ethics Commission',
                'company' => 'BPM HIMAIF - Telkom University',
                'description' => 'Supported organizational ethics monitoring, internal policy evaluation, and more structured decision-making.',
                'highlights' => [
                    'Supported code-of-ethics evaluation.',
                    'Participated in internal policy discussions.',
                ],
            ],
            [
                'period' => 'Jan 2025 - Dec 2025',
                'role' => 'President of the Student Club',
                'company' => 'UKM Paskibra Telkom University',
                'description' => 'Led planning, execution, and representation of the organization in both formal forums and internal programs.',
                'highlights' => [
                    'Coordinated members and work agendas.',
                    'Represented the organization in official forums.',
                ],
            ],
        ],
    ],
    'education' => [
        'id' => [
            [
                'period' => 'Sep 2023 - Sekarang',
                'title' => 'S1 Informatika',
                'institution' => 'Universitas Telkom',
                'description' => 'Mahasiswa Informatika dengan fokus pada machine learning, forecasting, NLP, analytics, dan fondasi backend yang mendukung implementasi project data.',
            ],
        ],
        'en' => [
            [
                'period' => 'Sep 2023 - Present',
                'title' => 'Bachelor of Informatics',
                'institution' => 'Telkom University',
                'description' => 'Informatics undergraduate interested in backend services, web development, machine learning, and presentable data work.',
            ],
        ],
    ],
    'projects' => [
        'id' => [
            [
                'name' => 'Portfolio Laravel',
                'stack' => 'Laravel, Blade, CSS, JavaScript',
                'category' => 'web',
                'description' => 'Rebuild web pribadi dari versi statis ke Laravel agar lebih rapi secara struktur, tetap interaktif, dan lebih mudah dipakai untuk menampilkan arah karier Data Scientist.',
                'highlight' => 'Menjadi rumah presentasi untuk project machine learning, forecasting, NLP, dan analytics yang saya kerjakan.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Portofolio'],
                ],
            ],
            [
                'name' => 'Sistem Order di Tempat QR System',
                'stack' => 'HTML, CSS, JavaScript',
                'category' => 'web',
                'description' => 'Sistem order di tempat berbasis QR untuk membantu pelanggan membuka menu dan mengikuti alur pemesanan langsung dari smartphone.',
                'highlight' => 'Membawa pengalaman pemesanan yang ringkas dan mudah dicoba dari perangkat mobile.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://raw.githack.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-/main/index.html'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-'],
                ],
            ],
            [
                'name' => 'revou-mini-project',
                'stack' => 'HTML, CSS',
                'category' => 'web',
                'description' => 'Mini project dari RevoU Coding Camp untuk menunjukkan fondasi pembuatan antarmuka web yang rapi dan responsif.',
                'highlight' => 'Menjadi salah satu pondasi awal perjalanan frontend saya.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://muhfajri24.github.io/revou-mini-project/'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/revou-mini-project'],
                ],
            ],
            [
                'name' => 'Customer Churn Prediction',
                'stack' => 'Python, Scikit-learn, XGBoost, Power BI',
                'category' => 'machine-learning',
                'description' => 'Workflow end-to-end untuk memprediksi churn pelanggan telco, membandingkan Logistic Regression, Random Forest, dan XGBoost, lalu menerjemahkannya menjadi rekomendasi retensi.',
                'highlight' => 'Model terbaik saat ini adalah Logistic Regression dengan ROC-AUC 0.8415 dan F1-Score 0.6274.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Churn-Prediction'],
                ],
            ],
            [
                'name' => 'Sales Forecasting',
                'stack' => 'Python, Prophet, ARIMA, Time Series',
                'category' => 'analytics',
                'description' => 'Workflow time series forecasting untuk memprediksi penjualan bulan berikutnya, membandingkan Prophet dan ARIMA, lalu menerjemahkan hasilnya menjadi insight perencanaan.',
                'highlight' => 'Menunjukkan validasi forecasting berbasis waktu dan pemilihan model terbaik untuk keputusan bisnis.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sales-Forecasting'],
                ],
            ],
            [
                'name' => 'Gojek Review Insight',
                'stack' => 'Python, NLP, TF-IDF, Streamlit',
                'category' => 'machine-learning',
                'description' => 'Workflow NLP untuk menganalisis ulasan aplikasi Gojek berbahasa Indonesia, mengklasifikasikan sentimen, dan menemukan tema keluhan yang dominan.',
                'highlight' => 'Menunjukkan pipeline text preprocessing, TF-IDF, model comparison, dan interpretasi insight dari review pengguna.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Gojek-Review-Insight'],
                ],
            ],
            [
                'name' => 'Customer Segmentation',
                'stack' => 'Python, K-Means, PCA, Streamlit, Power BI',
                'category' => 'analytics',
                'description' => 'Workflow unsupervised learning untuk mengelompokkan pelanggan berdasarkan perilaku belanja, mengevaluasi cluster, dan menghasilkan segment insight.',
                'highlight' => 'Menunjukkan segmentasi pelanggan dengan evaluasi cluster yang bisa dijelaskan ke stakeholder non-teknis.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Segmentation'],
                ],
            ],
            [
                'name' => 'Restaurant Sales Insight',
                'stack' => 'Python, SQL, Pandas, Power BI',
                'category' => 'analytics',
                'description' => 'Workflow analisis data untuk membersihkan data penjualan restoran, membangun KPI, menjalankan query SQL, dan menyiapkan output dashboard.',
                'highlight' => 'Menjadi fondasi analitis yang melengkapi project machine learning dengan data cleaning, KPI, dan reporting.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Restaurant-Sales-Insight'],
                ],
            ],
            [
                'name' => 'Artificial Intelligence Project',
                'stack' => 'Jupyter Notebook, Machine Learning',
                'category' => 'machine-learning',
                'description' => 'Project klasifikasi potabilitas air menggunakan KNN dan seleksi fitur berbasis Genetic Algorithm.',
                'highlight' => 'Menunjukkan fondasi eksplorasi AI sejak tahap awal pembelajaran.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Artficial_Intellegence_Project'],
                ],
            ],
            [
                'name' => 'employee-bonus-fuzzy-system',
                'stack' => 'Jupyter Notebook, Fuzzy Logic',
                'category' => 'machine-learning',
                'description' => 'Implementasi Fuzzy Inference System untuk menentukan bonus karyawan berdasarkan gaji dan performa.',
                'highlight' => 'Memperlihatkan cara saya menerjemahkan logika fuzzy ke kasus bisnis sederhana.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/employee-bonus-fuzzy-system'],
                ],
            ],
        ],
        'en' => [
            [
                'name' => 'Laravel Portfolio',
                'stack' => 'Laravel, Blade, CSS, JavaScript',
                'category' => 'web',
                'description' => 'A rebuild of my personal website from a static version into Laravel so the structure is cleaner, the interaction stays intact, and the site can present my Data Scientist direction more clearly.',
                'highlight' => 'Serves as the presentation layer for my machine learning, forecasting, NLP, and analytics work.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Portofolio'],
                ],
            ],
            [
                'name' => 'Dine-In QR Ordering System',
                'stack' => 'HTML, CSS, JavaScript',
                'category' => 'web',
                'description' => 'A dine-in QR ordering system that helps customers open the menu and follow the ordering flow directly from their smartphones.',
                'highlight' => 'Brings a compact and mobile-friendly ordering experience.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://raw.githack.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-/main/index.html'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-'],
                ],
            ],
            [
                'name' => 'revou-mini-project',
                'stack' => 'HTML, CSS',
                'category' => 'web',
                'description' => 'A mini project from RevoU Coding Camp that demonstrates an early foundation in clean and responsive web interfaces.',
                'highlight' => 'One of the earliest foundations of my frontend journey.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://muhfajri24.github.io/revou-mini-project/'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/revou-mini-project'],
                ],
            ],
            [
                'name' => 'Customer Churn Prediction',
                'stack' => 'Python, Scikit-learn, XGBoost, Power BI',
                'category' => 'machine-learning',
                'description' => 'An end-to-end workflow for telecom churn prediction that compares Logistic Regression, Random Forest, and XGBoost before turning the result into retention recommendations.',
                'highlight' => 'The current best model is Logistic Regression with ROC-AUC 0.8415 and F1-Score 0.6274.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Churn-Prediction'],
                ],
            ],
            [
                'name' => 'Sales Forecasting',
                'stack' => 'Python, Prophet, ARIMA, Time Series',
                'category' => 'analytics',
                'description' => 'A time series forecasting workflow for next-month sales prediction that compares Prophet and ARIMA before turning the output into planning insight.',
                'highlight' => 'Shows time-based validation and model selection for decision-oriented forecasting.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sales-Forecasting'],
                ],
            ],
            [
                'name' => 'Gojek Review Insight',
                'stack' => 'Python, NLP, TF-IDF, Streamlit',
                'category' => 'machine-learning',
                'description' => 'An NLP workflow for Indonesian Gojek app reviews that classifies sentiment and surfaces dominant complaint themes.',
                'highlight' => 'Shows text preprocessing, TF-IDF, model comparison, and user-review insight interpretation.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Gojek-Review-Insight'],
                ],
            ],
            [
                'name' => 'Customer Segmentation',
                'stack' => 'Python, K-Means, PCA, Streamlit, Power BI',
                'category' => 'analytics',
                'description' => 'An unsupervised learning workflow that groups customers by shopping behavior, evaluates cluster quality, and generates segment insight.',
                'highlight' => 'Shows customer segmentation with cluster evaluation that can be explained to non-technical stakeholders.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Segmentation'],
                ],
            ],
            [
                'name' => 'Restaurant Sales Insight',
                'stack' => 'Python, SQL, Pandas, Power BI',
                'category' => 'analytics',
                'description' => 'A data analysis workflow that cleans restaurant sales data, builds KPIs, runs SQL analysis, and prepares dashboard-ready outputs.',
                'highlight' => 'Acts as the analytical foundation that complements my machine learning projects with KPI, SQL, and reporting work.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Restaurant-Sales-Insight'],
                ],
            ],
            [
                'name' => 'Artificial Intelligence Project',
                'stack' => 'Jupyter Notebook, Machine Learning',
                'category' => 'machine-learning',
                'description' => 'A water-potability classification project using KNN and Genetic Algorithm-based feature selection.',
                'highlight' => 'Shows an early AI exploration foundation through a practical classification case.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Artficial_Intellegence_Project'],
                ],
            ],
            [
                'name' => 'employee-bonus-fuzzy-system',
                'stack' => 'Jupyter Notebook, Fuzzy Logic',
                'category' => 'machine-learning',
                'description' => 'A Fuzzy Inference System implementation for determining employee bonuses based on salary and performance.',
                'highlight' => 'Shows how I translate fuzzy logic into a simple business-oriented case.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/employee-bonus-fuzzy-system'],
                ],
            ],
        ],
    ],
    'contacts' => [
        'id' => [
            ['label' => 'Email', 'value' => 'muhfajrmlk@gmail.com', 'href' => 'mailto:muhfajrmlk@gmail.com'],
            ['label' => 'Telepon', 'value' => '0823-3318-8437', 'href' => 'tel:082333188437'],
            ['label' => 'GitHub', 'value' => 'github.com/muhfajri24', 'href' => 'https://github.com/muhfajri24'],
            ['label' => 'LinkedIn', 'value' => 'linkedin.com/in/muhammad-fajri-349821287', 'href' => 'https://www.linkedin.com/in/muhammad-fajri-349821287'],
        ],
        'en' => [
            ['label' => 'Email', 'value' => 'muhfajrmlk@gmail.com', 'href' => 'mailto:muhfajrmlk@gmail.com'],
            ['label' => 'Phone', 'value' => '0823-3318-8437', 'href' => 'tel:082333188437'],
            ['label' => 'GitHub', 'value' => 'github.com/muhfajri24', 'href' => 'https://github.com/muhfajri24'],
            ['label' => 'LinkedIn', 'value' => 'linkedin.com/in/muhammad-fajri-349821287', 'href' => 'https://www.linkedin.com/in/muhammad-fajri-349821287'],
        ],
    ],
];
