<?php

return [
    'links' => [
        'github' => 'https://github.com/muhfajri24',
        'linkedin' => 'https://www.linkedin.com/in/muhammad-fajri-349821287',
    ],
    'ui' => [
        'id' => [
            'lang' => 'id',
            'languageShort' => 'ID',
            'languageLabel' => 'Bahasa Indonesia',
            'nav' => [
                'about' => 'Tentang',
                'skills' => 'Skill',
                'experience' => 'Pengalaman',
                'education' => 'Pendidikan',
                'projects' => 'Proyek',
                'contact' => 'Kontak',
            ],
            'heroEyebrow' => 'Portfolio Laravel',
            'aboutEyebrow' => 'Tentang Saya',
            'aboutHeading' => 'Perjalanan teknis, organisasi, dan pembelajaran yang terus bergerak maju',
            'skillsEyebrow' => 'Skill',
            'skillsHeading' => 'Kemampuan teknis dan cara kerja yang saya bawa ke setiap kolaborasi',
            'experienceEyebrow' => 'Pengalaman',
            'experienceHeading' => 'Pengalaman profesional dan organisasi yang membentuk cara saya bekerja',
            'educationEyebrow' => 'Pendidikan',
            'educationHeading' => 'Fondasi akademik yang mendukung eksplorasi teknologi',
            'projectsEyebrow' => 'Proyek',
            'projectsHeading' => 'Project yang merekam proses belajar, eksekusi, dan dampak',
            'projectsDescription' => 'Portfolio ini tetap menjelaskan siapa saya dan perjalanan saya, lalu kini diperkuat dengan project machine learning dan analitik yang lebih matang dari folder project portfolio.',
            'projectFilterLabel' => 'Filter Project',
            'contactEyebrow' => 'Kontak',
            'contactHeading' => 'Mari terhubung untuk kolaborasi, internship, atau peluang kerja',
            'contactSummary' => 'Saya terbuka untuk backend development, web development, dan project berbasis data yang membutuhkan eksekusi teknis sekaligus komunikasi yang rapi.',
            'infoTitle' => 'Info Singkat',
            'noteLabel' => 'Fokus Saat Ini',
            'noteTitle' => 'Backend, web, dan data products',
            'noteText' => 'Saya menikmati proses mengubah masalah bisnis menjadi aplikasi, automasi, atau insight yang bisa digunakan.',
            'githubButton' => 'Lihat GitHub',
            'linkedinButton' => 'LinkedIn',
            'footer' => 'Dibangun ulang dengan Laravel, Blade, CSS, dan JavaScript agar struktur backend lebih rapi tanpa kehilangan pengalaman interaktif di sisi frontend.',
            'projectLink' => 'Highlight',
            'projectActions' => [
                'website' => 'Buka Demo',
                'repository' => 'Buka Repository',
            ],
            'projectFilters' => [
                ['value' => 'all', 'label' => 'Semua'],
                ['value' => 'web', 'label' => 'Web'],
                ['value' => 'machine-learning', 'label' => 'Machine Learning'],
                ['value' => 'analytics', 'label' => 'Analytics'],
            ],
            'stats' => [
                ['value' => '6+', 'label' => 'Pengalaman organisasi & profesional'],
                ['value' => '8', 'label' => 'Project publik & portfolio utama'],
                ['value' => '2023-', 'label' => 'Perjalanan akademik informatika'],
            ],
        ],
        'en' => [
            'lang' => 'en',
            'languageShort' => 'EN',
            'languageLabel' => 'English',
            'nav' => [
                'about' => 'About',
                'skills' => 'Skills',
                'experience' => 'Experience',
                'education' => 'Education',
                'projects' => 'Projects',
                'contact' => 'Contact',
            ],
            'heroEyebrow' => 'Laravel Portfolio',
            'aboutEyebrow' => 'About Me',
            'aboutHeading' => 'A growing journey across technical work, organizations, and continuous learning',
            'skillsEyebrow' => 'Skills',
            'skillsHeading' => 'Technical capabilities and working style I bring into each collaboration',
            'experienceEyebrow' => 'Experience',
            'experienceHeading' => 'Professional and organizational experiences that shape how I work',
            'educationEyebrow' => 'Education',
            'educationHeading' => 'Academic foundations that support my technology exploration',
            'projectsEyebrow' => 'Projects',
            'projectsHeading' => 'Projects that reflect learning, execution, and real-world value',
            'projectsDescription' => 'This portfolio still explains who I am and what I have been through, now strengthened with more complete machine learning and analytics projects sourced from the project portfolio folder.',
            'projectFilterLabel' => 'Project Filter',
            'contactEyebrow' => 'Contact',
            'contactHeading' => 'Let us connect for collaboration, internships, or career opportunities',
            'contactSummary' => 'I am open to backend development, web development, and data-oriented projects that need both technical execution and clear communication.',
            'infoTitle' => 'Quick Info',
            'noteLabel' => 'Current Focus',
            'noteTitle' => 'Backend, web, and data products',
            'noteText' => 'I enjoy turning business problems into applications, automations, or insights that people can actually use.',
            'githubButton' => 'View GitHub',
            'linkedinButton' => 'LinkedIn',
            'footer' => 'Rebuilt with Laravel, Blade, CSS, and JavaScript so the backend structure is cleaner without losing the interactive frontend experience.',
            'projectLink' => 'Highlight',
            'projectActions' => [
                'website' => 'Open Demo',
                'repository' => 'Open Repository',
            ],
            'projectFilters' => [
                ['value' => 'all', 'label' => 'All'],
                ['value' => 'web', 'label' => 'Web'],
                ['value' => 'machine-learning', 'label' => 'Machine Learning'],
                ['value' => 'analytics', 'label' => 'Analytics'],
            ],
            'stats' => [
                ['value' => '6+', 'label' => 'Professional and organizational roles'],
                ['value' => '8', 'label' => 'Public and flagship portfolio projects'],
                ['value' => '2023-', 'label' => 'Academic journey in informatics'],
            ],
        ],
    ],
    'personal' => [
        'name' => 'Muhammad Fajri',
        'image' => '/assets/Profile.jpeg',
        'role' => [
            'id' => 'Mahasiswa Informatika yang tumbuh lewat backend development, web engineering, dan project berbasis data.',
            'en' => 'An Informatics student growing through backend development, web engineering, and data-oriented projects.',
        ],
        'summary' => [
            'id' => 'Saya membangun portfolio ini untuk menunjukkan fondasi teknis yang rapi, keaktifan organisasi, dan bagaimana saya menerjemahkan pembelajaran menjadi produk digital serta analisis yang bisa dipresentasikan dengan jelas.',
            'en' => 'I built this portfolio to show a disciplined technical foundation, active organizational experience, and how I turn learning into digital products and clearly presentable analysis.',
        ],
        'about' => [
            'id' => 'Saya terbiasa belajar lewat studi kasus, mengerjakan project end-to-end, dan menjaga agar solusi tetap mudah dipahami. Pengalaman organisasi membuat saya nyaman memimpin, berkoordinasi, dan mengambil keputusan secara kolaboratif, sementara project teknis membuat saya terbiasa merapikan detail implementasi.',
            'en' => 'I am used to learning through case studies, completing projects end-to-end, and keeping solutions easy to understand. My organizational experience makes me comfortable leading, coordinating, and making collaborative decisions, while technical projects keep me disciplined around implementation details.',
        ],
        'currentLabel' => [
            'id' => 'Sorotan Peran',
            'en' => 'Featured Role',
        ],
        'currentTitle' => [
            'id' => 'Backend Developer Intern',
            'en' => 'Backend Developer Intern',
        ],
        'currentSubtitle' => [
            'id' => 'Telkom Indonesia | Januari 2026 - Mei 2026',
            'en' => 'Telkom Indonesia | January 2026 - May 2026',
        ],
        'highlights' => [
            'id' => [
                'Membangun ulang portfolio statis menjadi web Laravel dengan pengalaman frontend yang tetap hidup.',
                'Menambahkan project machine learning, analytics, dan NLP yang lebih kuat untuk kebutuhan presentasi portfolio.',
                'Aktif memimpin organisasi sekaligus menjaga pertumbuhan teknis lewat project nyata.',
            ],
            'en' => [
                'Rebuilt a static portfolio into a Laravel web app while preserving a lively frontend experience.',
                'Added stronger machine learning, analytics, and NLP projects for a more convincing portfolio story.',
                'Actively leads organizations while continuing technical growth through real projects.',
            ],
        ],
        'focus' => [
            'id' => ['Laravel', 'Backend Development', 'Machine Learning', 'Data Storytelling'],
            'en' => ['Laravel', 'Backend Development', 'Machine Learning', 'Data Storytelling'],
        ],
    ],
    'quickInfo' => [
        'id' => [
            ['title' => 'Domisili', 'value' => 'Kabupaten Bandung, Jawa Barat'],
            ['title' => 'Email', 'value' => 'muhfajrmlk@gmail.com'],
            ['title' => 'Telepon', 'value' => '0823-3318-8437'],
            ['title' => 'Alamat', 'value' => 'Bojongsoang, Bandung'],
            ['title' => 'Kampus', 'value' => 'Universitas Telkom'],
            ['title' => 'Fokus', 'value' => 'Backend, web, machine learning, dan analytics'],
        ],
        'en' => [
            ['title' => 'Location', 'value' => 'Bandung Regency, West Java'],
            ['title' => 'Email', 'value' => 'muhfajrmlk@gmail.com'],
            ['title' => 'Phone', 'value' => '0823-3318-8437'],
            ['title' => 'Address', 'value' => 'Bojongsoang, Bandung'],
            ['title' => 'University', 'value' => 'Telkom University'],
            ['title' => 'Focus', 'value' => 'Backend, web, machine learning, and analytics'],
        ],
    ],
    'skills' => [
        'id' => [
            ['title' => 'Backend & Framework', 'items' => ['Laravel', 'PHP', 'REST API Dasar', 'JSON']],
            ['title' => 'Bahasa Pemrograman', 'items' => ['Python', 'PHP', 'C++', 'Go']],
            ['title' => 'Machine Learning & AI', 'items' => ['Scikit-learn', 'XGBoost', 'NLP Dasar', 'Forecasting']],
            ['title' => 'Web Development', 'items' => ['HTML', 'CSS', 'JavaScript', 'Blade']],
            ['title' => 'Data & Visualisasi', 'items' => ['Pandas', 'Matplotlib', 'Seaborn', 'Power BI']],
            ['title' => 'Cara Kerja', 'items' => ['Analitis', 'Kepemimpinan', 'Kolaboratif', 'Adaptif']],
        ],
        'en' => [
            ['title' => 'Backend & Framework', 'items' => ['Laravel', 'PHP', 'Basic REST API', 'JSON']],
            ['title' => 'Programming Languages', 'items' => ['Python', 'PHP', 'C++', 'Go']],
            ['title' => 'Machine Learning & AI', 'items' => ['Scikit-learn', 'XGBoost', 'Basic NLP', 'Forecasting']],
            ['title' => 'Web Development', 'items' => ['HTML', 'CSS', 'JavaScript', 'Blade']],
            ['title' => 'Data & Visualization', 'items' => ['Pandas', 'Matplotlib', 'Seaborn', 'Power BI']],
            ['title' => 'Work Style', 'items' => ['Analytical', 'Leadership', 'Collaborative', 'Adaptive']],
        ],
    ],
    'experiences' => [
        'id' => [
            [
                'period' => 'Mar 2026 - Sekarang',
                'role' => 'Ketua BPM',
                'company' => 'BPM HIMAIF - Universitas Telkom',
                'description' => 'Memimpin badan legislatif HIMA IF serta menjaga arah kebijakan, pengawasan, dan koordinasi program kerja organisasi.',
                'highlights' => [
                    'Memimpin badan legislatif HIMA IF.',
                    'Menyelaraskan pengawasan organisasi dengan visi dan misi kelembagaan.',
                    'Berkoordinasi dengan dewan dan komite untuk menjaga eksekusi program kerja.',
                ],
            ],
            [
                'period' => 'Jan 2026 - Mei 2026',
                'role' => 'Magang Backend Developer',
                'company' => 'Telkom Indonesia',
                'description' => 'Berkontribusi pada integrasi layanan backend dan status monitoring perangkat untuk sistem chatbot selama masa magang.',
                'highlights' => [
                    'Membantu pembuatan API.',
                    'Mengelola data status perangkat seperti aktif, nonaktif, dan tidak terdeteksi.',
                    'Berkolaborasi dengan tim frontend pada widget obrolan dan dashboard monitoring.',
                ],
            ],
            [
                'period' => 'Apr 2025 - Mar 2026',
                'role' => 'Staff Ahli Komisi Etik',
                'company' => 'BPM HIMAIF - Universitas Telkom',
                'description' => 'Mendukung pemantauan kode etik organisasi, evaluasi kebijakan internal, dan pengambilan keputusan yang lebih terstruktur.',
                'highlights' => [
                    'Mendukung evaluasi kode etik organisasi.',
                    'Berpartisipasi dalam diskusi kebijakan internal.',
                ],
            ],
            [
                'period' => 'Jan 2025 - Des 2025',
                'role' => 'Ketua UKM Paskibra',
                'company' => 'UKM Paskibra Universitas Telkom',
                'description' => 'Memimpin perencanaan, eksekusi, dan representasi organisasi dalam forum resmi maupun kegiatan internal.',
                'highlights' => [
                    'Mengoordinasikan anggota dan agenda kerja.',
                    'Mewakili organisasi dalam forum resmi.',
                ],
            ],
        ],
        'en' => [
            [
                'period' => 'Mar 2026 - Present',
                'role' => 'Chair of the BPM',
                'company' => 'BPM HIMAIF - Telkom University',
                'description' => 'Leading the HIMA IF legislative body while maintaining policy direction, oversight, and work-program coordination.',
                'highlights' => [
                    'Leads the HIMA IF legislative body.',
                    'Aligns organizational oversight with institutional goals.',
                    'Coordinates with councils and committees to sustain program execution.',
                ],
            ],
            [
                'period' => 'Jan 2026 - May 2026',
                'role' => 'Backend Developer Intern',
                'company' => 'Telkom Indonesia',
                'description' => 'Contributed to backend service integration and device-status monitoring for a chatbot system during the internship.',
                'highlights' => [
                    'Helped build APIs.',
                    'Handled device-status data such as up, down, and undetected.',
                    'Collaborated with the frontend team on chat widgets and monitoring dashboards.',
                ],
            ],
            [
                'period' => 'Apr 2025 - Mar 2026',
                'role' => 'Senior Advisor to the Ethics Commission',
                'company' => 'BPM HIMAIF - Telkom University',
                'description' => 'Supported organizational ethics monitoring, internal policy evaluation, and more structured decision-making.',
                'highlights' => [
                    'Supported code-of-ethics evaluation.',
                    'Participated in internal policy discussions.',
                ],
            ],
            [
                'period' => 'Jan 2025 - Dec 2025',
                'role' => 'President of the Student Club',
                'company' => 'UKM Paskibra Telkom University',
                'description' => 'Led planning, execution, and representation of the organization in both formal forums and internal programs.',
                'highlights' => [
                    'Coordinated members and work agendas.',
                    'Represented the organization in official forums.',
                ],
            ],
        ],
    ],
    'education' => [
        'id' => [
            [
                'period' => 'Sep 2023 - Sekarang',
                'title' => 'S1 Informatika',
                'institution' => 'Universitas Telkom',
                'description' => 'Mahasiswa Informatika dengan ketertarikan pada backend service, web development, machine learning, dan pengolahan data yang siap dipresentasikan.',
            ],
        ],
        'en' => [
            [
                'period' => 'Sep 2023 - Present',
                'title' => 'Bachelor of Informatics',
                'institution' => 'Telkom University',
                'description' => 'Informatics undergraduate interested in backend services, web development, machine learning, and presentable data work.',
            ],
        ],
    ],
    'projects' => [
        'id' => [
            [
                'name' => 'Portfolio Laravel',
                'stack' => 'Laravel, Blade, CSS, JavaScript',
                'category' => 'web',
                'description' => 'Rebuild portfolio pribadi dari web statis menjadi Laravel agar struktur backend lebih rapi, tetap interaktif, dan lebih siap dikembangkan lagi.',
                'highlight' => 'Interaktivitas lama dipertahankan, lalu ditambah struktur server-side dan visual yang lebih elegan.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Portofolio'],
                ],
            ],
            [
                'name' => 'Sistem Order di Tempat QR System',
                'stack' => 'HTML, CSS, JavaScript',
                'category' => 'web',
                'description' => 'Sistem order di tempat berbasis QR untuk membantu pelanggan membuka menu dan mengikuti alur pemesanan langsung dari smartphone.',
                'highlight' => 'Membawa pengalaman pemesanan yang ringkas dan mudah dicoba dari perangkat mobile.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://raw.githack.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-/main/index.html'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-'],
                ],
            ],
            [
                'name' => 'revou-mini-project',
                'stack' => 'HTML, CSS',
                'category' => 'web',
                'description' => 'Mini project dari RevoU Coding Camp untuk menunjukkan fondasi pembuatan antarmuka web yang rapi dan responsif.',
                'highlight' => 'Menjadi salah satu pondasi awal perjalanan frontend saya.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://muhfajri24.github.io/revou-mini-project/'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/revou-mini-project'],
                ],
            ],
            [
                'name' => 'Customer Churn Prediction',
                'stack' => 'Python, Scikit-learn, XGBoost, Power BI',
                'category' => 'machine-learning',
                'description' => 'Workflow end-to-end untuk memprediksi churn pelanggan telco, membandingkan Logistic Regression, Random Forest, dan XGBoost, lalu menerjemahkannya menjadi rekomendasi retensi.',
                'highlight' => 'Model terbaik saat ini adalah Logistic Regression dengan ROC-AUC 0.8415 dan F1-Score 0.6274.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Churn-Prediction'],
                ],
            ],
            [
                'name' => 'Customer Segmentation',
                'stack' => 'Python, K-Means, PCA, Streamlit, Power BI',
                'category' => 'analytics',
                'description' => 'Project segmentasi pelanggan berbasis unsupervised learning untuk memetakan perilaku belanja, memvalidasi jumlah cluster, dan menghasilkan segment insight yang mudah dipresentasikan.',
                'highlight' => 'Jumlah cluster terbaik adalah 8 dengan silhouette score 0.3880 dan visualisasi PCA untuk storytelling.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Segmentation'],
                ],
            ],
            [
                'name' => 'Gojek Review Insight',
                'stack' => 'Python, NLP, TF-IDF, Streamlit',
                'category' => 'machine-learning',
                'description' => 'Analisis sentimen ulasan aplikasi Gojek berbahasa Indonesia untuk memetakan distribusi sentimen, tema keluhan, dan model klasifikasi terbaik.',
                'highlight' => 'Naive Bayes menjadi model terbaik dengan F1-Score 0.8818 dari 6.152 ulasan yang diproses.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Gojek-Review-Insight'],
                ],
            ],
            [
                'name' => 'Sales Forecasting',
                'stack' => 'Python, Prophet, ARIMA, Time Series',
                'category' => 'analytics',
                'description' => 'Forecasting penjualan bulan berikutnya dari dataset Rossmann dengan validasi time-based, perbandingan model Prophet vs ARIMA, dan rangkuman bisnis yang siap presentasi.',
                'highlight' => 'Prophet menjadi model terbaik dengan forecast total sales sekitar 200,9 juta untuk bulan prediksi.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sales-Forecasting'],
                ],
            ],
            [
                'name' => 'Artificial Intelligence Project',
                'stack' => 'Jupyter Notebook, Machine Learning',
                'category' => 'machine-learning',
                'description' => 'Proyek klasifikasi potabilitas air menggunakan KNN dan seleksi fitur berbasis Genetic Algorithm.',
                'highlight' => 'Menunjukkan fondasi eksplorasi AI sejak tahap awal pembelajaran.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Artficial_Intellegence_Project'],
                ],
            ],
            [
                'name' => 'employee-bonus-fuzzy-system',
                'stack' => 'Jupyter Notebook, Fuzzy Logic',
                'category' => 'machine-learning',
                'description' => 'Implementasi Fuzzy Inference System untuk menentukan bonus karyawan berdasarkan gaji dan performa.',
                'highlight' => 'Memperlihatkan cara saya menerjemahkan logika fuzzy ke kasus bisnis sederhana.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/employee-bonus-fuzzy-system'],
                ],
            ],
        ],
        'en' => [
            [
                'name' => 'Laravel Portfolio',
                'stack' => 'Laravel, Blade, CSS, JavaScript',
                'category' => 'web',
                'description' => 'A rebuild of my personal portfolio from a static website into Laravel so the backend structure is cleaner while the site stays interactive and ready to grow.',
                'highlight' => 'The existing interactivity is preserved and strengthened with a cleaner server-side structure and a more elegant visual language.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Portofolio'],
                ],
            ],
            [
                'name' => 'Dine-In QR Ordering System',
                'stack' => 'HTML, CSS, JavaScript',
                'category' => 'web',
                'description' => 'A dine-in QR ordering system that helps customers open the menu and follow the ordering flow directly from their smartphones.',
                'highlight' => 'Brings a compact and mobile-friendly ordering experience.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://raw.githack.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-/main/index.html'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sistem-Order-di-Tempat-QR-System-'],
                ],
            ],
            [
                'name' => 'revou-mini-project',
                'stack' => 'HTML, CSS',
                'category' => 'web',
                'description' => 'A mini project from RevoU Coding Camp that demonstrates an early foundation in clean and responsive web interfaces.',
                'highlight' => 'One of the earliest foundations of my frontend journey.',
                'links' => [
                    ['type' => 'website', 'href' => 'https://muhfajri24.github.io/revou-mini-project/'],
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/revou-mini-project'],
                ],
            ],
            [
                'name' => 'Customer Churn Prediction',
                'stack' => 'Python, Scikit-learn, XGBoost, Power BI',
                'category' => 'machine-learning',
                'description' => 'An end-to-end workflow for telecom churn prediction that compares Logistic Regression, Random Forest, and XGBoost before turning the result into retention recommendations.',
                'highlight' => 'The current best model is Logistic Regression with ROC-AUC 0.8415 and F1-Score 0.6274.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Churn-Prediction'],
                ],
            ],
            [
                'name' => 'Customer Segmentation',
                'stack' => 'Python, K-Means, PCA, Streamlit, Power BI',
                'category' => 'analytics',
                'description' => 'A customer-segmentation project that uses unsupervised learning to map shopping behavior, validate cluster counts, and generate presentation-ready segment insights.',
                'highlight' => 'The best cluster count is 8 with a silhouette score of 0.3880 and PCA storytelling visuals.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Customer-Segmentation'],
                ],
            ],
            [
                'name' => 'Gojek Review Insight',
                'stack' => 'Python, NLP, TF-IDF, Streamlit',
                'category' => 'machine-learning',
                'description' => 'An Indonesian-language sentiment-analysis project for Gojek app reviews that surfaces sentiment distribution, complaint themes, and the strongest classification model.',
                'highlight' => 'Naive Bayes is the best model with an F1-Score of 0.8818 across 6,152 processed reviews.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Gojek-Review-Insight'],
                ],
            ],
            [
                'name' => 'Sales Forecasting',
                'stack' => 'Python, Prophet, ARIMA, Time Series',
                'category' => 'analytics',
                'description' => 'A next-month sales forecasting project using the Rossmann dataset, time-based validation, Prophet vs ARIMA comparison, and business-ready reporting.',
                'highlight' => 'Prophet is the selected model with an expected forecast total of about 200.9 million for the predicted month.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Sales-Forecasting'],
                ],
            ],
            [
                'name' => 'Artificial Intelligence Project',
                'stack' => 'Jupyter Notebook, Machine Learning',
                'category' => 'machine-learning',
                'description' => 'A water-potability classification project using KNN and Genetic Algorithm-based feature selection.',
                'highlight' => 'Shows an early AI exploration foundation through a practical classification case.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/Artficial_Intellegence_Project'],
                ],
            ],
            [
                'name' => 'employee-bonus-fuzzy-system',
                'stack' => 'Jupyter Notebook, Fuzzy Logic',
                'category' => 'machine-learning',
                'description' => 'A Fuzzy Inference System implementation for determining employee bonuses based on salary and performance.',
                'highlight' => 'Shows how I translate fuzzy logic into a simple business-oriented case.',
                'links' => [
                    ['type' => 'repository', 'href' => 'https://github.com/muhfajri24/employee-bonus-fuzzy-system'],
                ],
            ],
        ],
    ],
    'contacts' => [
        'id' => [
            ['label' => 'Email', 'value' => 'muhfajrmlk@gmail.com', 'href' => 'mailto:muhfajrmlk@gmail.com'],
            ['label' => 'Telepon', 'value' => '0823-3318-8437', 'href' => 'tel:082333188437'],
            ['label' => 'GitHub', 'value' => 'github.com/muhfajri24', 'href' => 'https://github.com/muhfajri24'],
            ['label' => 'LinkedIn', 'value' => 'linkedin.com/in/muhammad-fajri-349821287', 'href' => 'https://www.linkedin.com/in/muhammad-fajri-349821287'],
        ],
        'en' => [
            ['label' => 'Email', 'value' => 'muhfajrmlk@gmail.com', 'href' => 'mailto:muhfajrmlk@gmail.com'],
            ['label' => 'Phone', 'value' => '0823-3318-8437', 'href' => 'tel:082333188437'],
            ['label' => 'GitHub', 'value' => 'github.com/muhfajri24', 'href' => 'https://github.com/muhfajri24'],
            ['label' => 'LinkedIn', 'value' => 'linkedin.com/in/muhammad-fajri-349821287', 'href' => 'https://www.linkedin.com/in/muhammad-fajri-349821287'],
        ],
    ],
];
